n="hello world"
print(n.split(sep=","))
print(n.upper())
print(n.lower())
print(n.swapcase())
f=("this is python")
print(n + "!! " + f)
print(b"ciao")
if (f.endswith("!")):print ("True") 
else:print("False")
